### PR TITLE
Add a :popover options to present the alert from popover

### PR DESCRIPTION
**Pull request by bmichotte**
Present the alert from a popover, by passing a `:popover` option and provide the source (either a UIView or a UIBarButtonItem)
```ruby
rmq.append(UIButton, :my_button).on(:tap) do |sender|
  rmq.app.alert(title: "Actions!", message: "Alert from a Popover.", actions: [:ok, :cancel], popover: sender)
end
```

The popover stuff is ignored on iPhone.

### CODE REVIEW

**Comment by GantMan** [comment]
very cool!   Can't wait to check this out.  Does it work on iOS7 and iOS8?

**Comment by bmichotte** [comment]
Yes, I made the modification for both

**Comment by GantMan** [comment]
busy week, will review soon.

**Comment by GantMan** [comment]
you should have the merge resolution in your repo as a PR.

**Comment by bmichotte** [comment]
I close this one, because of https://github.com/GantMan/RedAlert/pull/17

**Pull request closed without merging**
